version: "3.8"
services:
  db_test:
    image: mysql:8.0
    container_name: GameAffinity_Test
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: gameaffinity_test_db
    ports:
      - "3307:3306"
    volumes:
      - ./app/src/main/resources/db/test_setup.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
