version: "3.8"
services:
  db:
    image: mysql:8.0
    container_name: GameAffinity
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: gameaffinity_db
    ports:
      - "3306:3306"
    volumes:
      - ./app/src/main/resources/db/setup.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
